"""
app_grid.py — Algeria Green Hydrogen LCOH Grid Map
Streamlit application for researchers.

Requires: data/lcoh_grid.csv (generated by pypsa_grid.py)
Run:      streamlit run app_grid.py
"""

import warnings
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

warnings.filterwarnings("ignore")

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Algeria H₂ LCOH Map",
    page_icon="🇩🇿",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── CSS ───────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@400;600;700;800&display=swap');
:root {
    --bg:#070d1a; --bg2:#0d1829; --bg3:#111f35;
    --border:#1e3050; --amber:#f5a623; --amber2:#ffd07a;
    --teal:#00d4b8; --red:#ff4d6d; --text:#c8d8f0;
    --muted:#5a7a9a; --white:#eaf2ff;
}
html,body,[data-testid="stAppViewContainer"]{background:var(--bg)!important;color:var(--text)!important;font-family:'Syne',sans-serif;}
[data-testid="stSidebar"]{background:var(--bg2)!important;border-right:1px solid var(--border);}
[data-testid="stSidebar"] *{color:var(--text)!important;}
h1,h2,h3{font-family:'Syne',sans-serif!important;color:var(--white)!important;}
[data-testid="metric-container"]{background:var(--bg3)!important;border:1px solid var(--border)!important;border-radius:8px!important;padding:12px 16px!important;}
[data-testid="metric-container"] label{color:var(--muted)!important;font-size:11px!important;letter-spacing:.08em;text-transform:uppercase;}
[data-testid="metric-container"] [data-testid="stMetricValue"]{color:var(--amber)!important;font-family:'Space Mono',monospace!important;font-size:1.5rem!important;}
.stButton>button{background:linear-gradient(135deg,var(--amber),#e08800)!important;color:#070d1a!important;font-family:'Space Mono',monospace!important;font-weight:700!important;border:none!important;border-radius:6px!important;padding:10px 24px!important;width:100%;}
[data-testid="stSelectbox"]>div>div{background:var(--bg3)!important;border:1px solid var(--border)!important;color:var(--white)!important;border-radius:6px!important;}
[data-testid="stTabs"] button{font-family:'Space Mono',monospace!important;font-size:12px!important;color:var(--muted)!important;letter-spacing:.06em;}
[data-testid="stTabs"] button[aria-selected="true"]{color:var(--amber)!important;border-bottom:2px solid var(--amber)!important;}
.info-box{background:var(--bg3);border-left:3px solid var(--amber);border-radius:0 8px 8px 0;padding:12px 16px;margin:8px 0;font-size:13px;}
.warn-box{background:#1a0d0d;border-left:3px solid var(--red);border-radius:0 8px 8px 0;padding:12px 16px;margin:8px 0;font-size:13px;color:#ffaaaa;}
.section-title{font-family:'Space Mono',monospace;font-size:11px;letter-spacing:.15em;color:var(--muted);text-transform:uppercase;border-bottom:1px solid var(--border);padding-bottom:6px;margin:20px 0 12px 0;}
.stat-card{background:var(--bg3);border:1px solid var(--border);border-radius:8px;padding:16px;text-align:center;}
.stat-card .val{font-family:'Space Mono',monospace;font-size:1.4rem;color:var(--amber);}
.stat-card .lbl{font-size:11px;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-top:4px;}
#MainMenu,footer,header{visibility:hidden;}
.block-container{padding-top:1.5rem!important;}
</style>
""", unsafe_allow_html=True)

PLOT_BG = dict(paper_bgcolor="#0d1829", plot_bgcolor="#070d1a",
               font=dict(family="Space Mono, monospace", color="#c8d8f0", size=11),
               margin=dict(l=10, r=10, t=40, b=10))

# ── Data loading ──────────────────────────────────────────────────────────────
# DATA SOURCE: The data comes from local CSV files in the 'data' directory.
# - lcoh_grid.csv: Contains precomputed LCOH values for each grid cell (generated by 'pypsa_grid.py').
# - grid_cf_stats.csv: Contains solar/wind capacity factors from ERA5 weather data (generated by 'atlite_grid.py').
DATA_DIR    = __import__("pathlib").Path(__file__).parent / "data"
GRID_PATH   = DATA_DIR / "lcoh_grid.csv"
STATS_PATH  = DATA_DIR / "grid_cf_stats.csv"

@st.cache_data
def load_grid() -> pd.DataFrame:
    if not GRID_PATH.exists():
        return pd.DataFrame()
    df = pd.read_csv(GRID_PATH)
    df = df[df["lcoh_usd_per_kg"].notna() & (df["lcoh_usd_per_kg"] < 50)]
    return df

@st.cache_data
def load_stats() -> pd.DataFrame:
    if not STATS_PATH.exists():
        return pd.DataFrame()
    return pd.read_csv(STATS_PATH, index_col=0)

# ── Financial rescaling ───────────────────────────────────────────────────────
def rescale_lcoh(
    base_df:        pd.DataFrame,
    new_discount:   float,
    new_lifetime:   int,
    new_solar_capex:float,
    new_wind_capex: float,
    new_elec_capex: float,
    new_bat_capex:  float,
    new_elec_eff:   float,
    new_grid_price: float,
    new_dzd_usd:    float,
    base_discount:  float = 0.08,
    base_lifetime:  int   = 25,
    base_solar_capex:float= 600.0,
    base_wind_capex:float = 1100.0,
    base_elec_capex:float = 700.0,
    base_bat_capex: float = 250.0,
    base_elec_eff:  float = 55.0,
    base_grid_price:float = 9.0,
    base_dzd_usd:   float = 134.5,
) -> pd.DataFrame:
    """
    Analytically rescale LCOH from base parameters to new parameters.

    LCOH = (C_solar + C_wind + C_elec + C_h2t + C_bat + C_grid) / H2_kg

    We rescale only the components that changed:
      - Solar capex → affects C_solar proportionally
      - Electrolyzer capex → affects C_elec proportionally
      - Discount rate / lifetime → affects all CAPEX via CRF ratio
      - Grid price → affects C_grid
      - Electrolyzer efficiency → affects C_elec (kWh/kg changes)
    """
    df = base_df.copy()

    def crf(r, n):
        if r == 0: return 1/n
        return r*(1+r)**n / ((1+r)**n - 1)

    crf_ratio   = crf(new_discount, new_lifetime) / crf(base_discount, base_lifetime)
    solar_ratio = new_solar_capex / base_solar_capex
    wind_ratio  = new_wind_capex / base_wind_capex
    elec_ratio  = (new_elec_capex * (new_elec_eff / base_elec_eff)) / base_elec_capex
    bat_ratio   = new_bat_capex / base_bat_capex
    grid_ratio  = (new_grid_price / new_dzd_usd) / (base_grid_price / base_dzd_usd)

    # Reconstruct scaled costs per kg
    df["cost_solar_scaled"]  = df["cost_solar"]      * crf_ratio * solar_ratio
    df["cost_wind_scaled"]   = df["cost_wind"]       * crf_ratio * wind_ratio
    df["cost_elec_scaled"]   = df["cost_electrolyzer"]* crf_ratio * elec_ratio
    df["cost_h2t_scaled"]    = df["cost_h2_storage"] * crf_ratio
    df["cost_bat_scaled"]    = df["cost_battery"]    * crf_ratio * bat_ratio
    df["cost_grid_scaled"]   = df["cost_grid"]       * grid_ratio

    # Sum → new total cost → new LCOH
    df["total_scaled"] = (df["cost_solar_scaled"] + df["cost_wind_scaled"] +
                          df["cost_elec_scaled"]  + df["cost_h2t_scaled"]  +
                          df["cost_bat_scaled"]   + df["cost_grid_scaled"])

    h2_kg = df["h2_produced_kg"].replace(0, np.nan)
    df["lcoh_scaled"] = df["total_scaled"] / h2_kg
    df["lcoh_dzd_scaled"] = df["lcoh_scaled"] * new_dzd_usd
    return df

# ══════════════════════════════════════════════════════════════════════════════
#  SIDEBAR
# ══════════════════════════════════════════════════════════════════════════════
with st.sidebar:
    st.markdown("## 🇩🇿 H₂ LCOH Grid Map")
    st.markdown("<div style='color:#5a7a9a;font-size:12px;margin-bottom:16px'>Algeria — Research Tool</div>", unsafe_allow_html=True)

    # Data status
    grid_df   = load_grid()
    stats_df  = load_stats()
    has_data  = len(grid_df) > 0

    if has_data:
        st.markdown(f"<div class='info-box'>✅ Grid data loaded — <b>{len(grid_df)} cells</b></div>", unsafe_allow_html=True)
    else:
        st.markdown("""<div class='warn-box'>
            ⚠️ No precomputed grid found.<br>
            Run first:<br>
            <code>python atlite_grid.py --key YOUR_KEY</code><br>
            <code>python pypsa_grid.py</code>
        </div>""", unsafe_allow_html=True)

    # ── Map display options ───────────────────────────────────────────────────
    # VARIABLES: UI state variables that determine which column to plot on the map and which color scheme to use.
    st.markdown("<div class='section-title'>🗺️ Map Display</div>", unsafe_allow_html=True)
    map_metric = st.selectbox("Color by", [
        "LCOH (USD/kg H₂)",
        "LCOH (DZD/kg H₂)",
        "Solar Full Load Hours",
        "Wind CF Mean",
        "Renewable Share (%)",
        "Electrolyzer Utilization (%)",
        "Solar Capacity (kW)",
    ])
    colorscale = st.selectbox("Color scale", [
        "RdYlGn_r", "Viridis", "Plasma", "Turbo", "RdBu_r", "YlOrRd",
    ], index=0)
    show_grid_lines = st.toggle("Show grid lines", value=True)

    # ── Financial parameters ──────────────────────────────────────────────────
    # VARIABLES: These are user-adjustable financial variables from the sidebar sliders.
    # They are passed to 'rescale_lcoh()' to instantly recalculate cost scenarios mathematically.
    st.markdown("<div class='section-title'>💰 Financials</div>", unsafe_allow_html=True)
    discount_rate    = st.slider("Discount Rate / WACC (%)", 3, 20, 8) / 100
    project_lifetime = st.slider("Project Lifetime (yr)", 10, 30, 25)
    grid_price_dzd   = st.slider("Grid Price (DZD/kWh)", 3.0, 25.0, 9.0, 0.5)
    dzd_to_usd       = st.number_input("DZD / USD", value=134.5, step=1.0)

    # ── Technology costs ──────────────────────────────────────────────────────
    # VARIABLES: Hardware cost variables from the sidebar. Changing these adjusts
    # the proportional capital costs in the pre-calculated dataframe.
    st.markdown("<div class='section-title'>⚙️ Technology Costs</div>", unsafe_allow_html=True)
    solar_capex     = st.slider("Solar CAPEX (USD/kW)",     200, 1500, 600, 25)
    wind_capex      = st.slider("Wind CAPEX (USD/kW)",      500, 2000, 1100, 50)
    elec_capex      = st.slider("Electrolyzer CAPEX (USD/kW)", 200, 2000, 700, 50)
    bat_capex       = st.slider("Battery CAPEX (USD/kWh)",  100, 800, 250, 10)
    elec_efficiency = st.slider("Electrolyzer Efficiency (kWh/kg H₂)", 40.0, 80.0, 55.0, 1.0)

    st.markdown("---")
    apply_btn = st.button("🔄 APPLY TO MAP", width="stretch")

    # ── Export ────────────────────────────────────────────────────────────────
    st.markdown("<div class='section-title'>📥 Export</div>", unsafe_allow_html=True)
    if has_data and st.button("⬇️ Download CSV", width="stretch"):
        st.download_button(
            "Download lcoh_grid.csv",
            data=grid_df.to_csv(index=False),
            file_name="algeria_lcoh_grid.csv",
            mime="text/csv",
        )

# ══════════════════════════════════════════════════════════════════════════════
#  HEADER
# ══════════════════════════════════════════════════════════════════════════════
st.markdown("# 🇩🇿 Algeria — Green Hydrogen LCOH Grid Map")
st.markdown(
    "<p style='color:#5a7a9a;margin-top:-12px;font-size:14px'>"
    "Spatial Levelized Cost of Hydrogen · ERA5 Weather · PyPSA Optimization</p>",
    unsafe_allow_html=True
)

# ══════════════════════════════════════════════════════════════════════════════
#  MAIN CONTENT
# ══════════════════════════════════════════════════════════════════════════════
if not has_data:
    st.markdown("---")
    st.markdown("### ⚙️ Setup Instructions")
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown("""<div class='info-box'>
        <b>Step 1 — Get CDS API key</b><br><br>
        Register free at<br>
        <a href='https://cds.climate.copernicus.eu' target='_blank'>cds.climate.copernicus.eu</a><br><br>
        Accept ERA5 dataset terms on the same site.
        </div>""", unsafe_allow_html=True)
    with c2:
        st.markdown("""<div class='info-box'>
        <b>Step 2 — Download ERA5 + extract CFs</b><br><br>
        <code>python atlite_grid.py --key YOUR_KEY</code><br><br>
        Downloads ~2-4 GB. Takes 10-30 min.<br>
        Only needed once.
        </div>""", unsafe_allow_html=True)
    with c3:
        st.markdown("""<div class='info-box'>
        <b>Step 3 — Precompute LCOH grid</b><br><br>
        <code>python pypsa_grid.py</code><br><br>
        Solves ~281 cells × PyPSA.<br>
        Takes ~9 min. Only needed once.
        </div>""", unsafe_allow_html=True)

    st.info("After running both scripts, refresh this page to load the results.")
    st.stop()

# ── Rescale LCOH based on sidebar params ─────────────────────────────────────
if "scaled_df" not in st.session_state or apply_btn:
    with st.spinner("Rescaling LCOH for all grid cells..."):
        scaled_df = rescale_lcoh(
            base_df=grid_df,
            new_discount=discount_rate,
            new_lifetime=project_lifetime,
            new_solar_capex=solar_capex,
            new_wind_capex=wind_capex,
            new_elec_capex=elec_capex,
            new_bat_capex=bat_capex,
            new_elec_eff=elec_efficiency,
            new_grid_price=grid_price_dzd,
            new_dzd_usd=dzd_to_usd,
        )
        st.session_state.scaled_df = scaled_df

scaled_df = st.session_state.scaled_df

# ── Summary metrics ───────────────────────────────────────────────────────────
valid = scaled_df[scaled_df["lcoh_scaled"].notna() & (scaled_df["lcoh_scaled"] < 50)]
m1, m2, m3, m4, m5 = st.columns(5)
m1.metric("🏆 Min LCOH",  f"${valid['lcoh_scaled'].min():.2f}/kg")
m2.metric("📊 Mean LCOH", f"${valid['lcoh_scaled'].mean():.2f}/kg")
m3.metric("📈 Max LCOH",  f"${valid['lcoh_scaled'].max():.2f}/kg")
m4.metric("🔢 Grid Cells", f"{len(valid)}")
m5.metric("♻️ Max Renew.", f"{valid['pct_renewable'].max():.0f}%")

st.markdown("---")

# ── Tabs ──────────────────────────────────────────────────────────────────────
tab1, tab2, tab3 = st.tabs(["🗺️ LCOH MAP", "☀️ SOLAR RESOURCE", "📊 STATISTICS"])

# ══════════════════════════════════════════════════════════════════════════════
#  TAB 1 — LCOH MAP
# ══════════════════════════════════════════════════════════════════════════════
with tab1:

    # Map metric column selector
    metric_col_map = {
        "LCOH (USD/kg H₂)":          ("lcoh_scaled",                 "LCOH USD/kg"),
        "LCOH (DZD/kg H₂)":          ("lcoh_dzd_scaled",             "LCOH DZD/kg"),
        "Solar Full Load Hours":      ("solar_full_load_hours",       "FLH/yr"),
        "Wind CF Mean":               ("wind_cf_mean",                "Wind CF"),
        "Renewable Share (%)":        ("pct_renewable",               "Renew. %"),
        "Electrolyzer Utilization (%)":("electrolyzer_utilization_pct","Elec. util %"),
        "Solar Capacity (kW)":        ("solar_capacity_kw",           "Solar kW"),
    }
    col_name, col_label = metric_col_map[map_metric]

    # Use lcoh_scaled or fall back to available column
    if col_name not in scaled_df.columns:
        col_name = "lcoh_usd_per_kg"
        col_label = "LCOH USD/kg"

    plot_df = scaled_df[scaled_df[col_name].notna()].copy()
    z_vals  = plot_df[col_name].values

    # ── Build grid heatmap using filled rectangles ────────────────────────────
    # Each 1° cell rendered as a filled square on the map
    fig = go.Figure()

    # Colored grid cells
    fig.add_trace(go.Scattermapbox(
        lat=plot_df["lat"],
        lon=plot_df["lon"],
        mode="markers",
        marker=dict(
            size=22,
            color=z_vals,
            colorscale=colorscale,
            colorbar=dict(
                title=dict(text=col_label, font=dict(color="#c8d8f0", size=11)),
                tickfont=dict(color="#c8d8f0"),
                bgcolor="#0d1829",
                bordercolor="#1e3050",
                thickness=14,
            ),
            opacity=0.85,
            symbol="square",
        ),
        text=[
            f"<b>Cell {row['cell_id']}</b><br>"
            f"Lat: {row['lat']:.1f}° N, Lon: {row['lon']:.1f}° E<br>"
            f"LCOH: ${row.get('lcoh_scaled', row['lcoh_usd_per_kg']):.3f}/kg H₂<br>"
            f"LCOH: {row.get('lcoh_dzd_scaled', row.get('lcoh_dzd_per_kg',0)):.0f} DZD/kg<br>"
            f"Solar FLH: {row.get('solar_full_load_hours',0):.0f} h/yr<br>"
            f"Renewable: {row.get('pct_renewable',0):.1f}%"
            for _, row in plot_df.iterrows()
        ],
        hoverinfo="text",
        name=col_label,
    ))

    fig.update_layout(
        **PLOT_BG,
        mapbox=dict(
            style="carto-darkmatter",
            center=dict(lat=28.0, lon=2.5),
            zoom=4.2,
        ),
        height=620,
        showlegend=False,
        title=dict(
            text=f"Algeria — {map_metric}",
            font=dict(color="#f5a623", size=14, family="Space Mono"),
            x=0.01,
        ),
    )

    st.plotly_chart(fig, width="stretch")

    # ── Best zones callout ────────────────────────────────────────────────────
    # TABLE SECTION: Displays a small dataframe table showing the top 5 grid cells with the lowest LCOH.
    # This is found at the bottom of Tab 1 below the map.
    best5 = valid.nsmallest(5, "lcoh_scaled")[
        ["lat","lon","lcoh_scaled","lcoh_dzd_scaled","solar_full_load_hours","pct_renewable"]
    ].round({"lcoh_scaled":3,"lcoh_dzd_scaled":0,"solar_full_load_hours":0,"pct_renewable":1})
    best5.columns = ["Lat","Lon","LCOH USD/kg","LCOH DZD/kg","Solar FLH","Renew. %"]

    st.markdown("#### 🏆 Top 5 Lowest-LCOH Grid Cells")
    st.dataframe(best5, width="stretch", hide_index=True)

# ══════════════════════════════════════════════════════════════════════════════
#  TAB 2 — SOLAR RESOURCE MAP
# ══════════════════════════════════════════════════════════════════════════════
with tab2:
    if len(stats_df) > 0:
        flh_col  = "solar_full_load_hours"
        wcf_col  = "wind_cf_mean"

        c_left, c_right = st.columns(2)

        with c_left:
            st.markdown("#### ☀️ Solar Full Load Hours")
            fig_sol = go.Figure(go.Scattermapbox(
                lat=stats_df["lat"], lon=stats_df["lon"],
                mode="markers",
                marker=dict(
                    size=20, symbol="square",
                    color=stats_df[flh_col],
                    colorscale="YlOrRd",
                    colorbar=dict(title="FLH/yr", tickfont=dict(color="#c8d8f0"),
                                  thickness=12, bgcolor="#0d1829"),
                    opacity=0.85,
                ),
                text=[f"<b>{idx}</b><br>FLH: {row[flh_col]:.0f} h/yr<br>CF mean: {row['solar_cf_mean']:.3f}"
                      for idx, row in stats_df.iterrows()],
                hoverinfo="text",
            ))
            fig_sol.update_layout(
                **PLOT_BG,
                mapbox=dict(style="carto-darkmatter", center=dict(lat=28,lon=2.5), zoom=3.8),
                height=420,
                title=dict(text="Solar PV Full Load Hours (ERA5)", font=dict(color="#f5a623",size=12)),
            )
            st.plotly_chart(fig_sol, width="stretch")

        with c_right:
            st.markdown("#### 💨 Wind Capacity Factor")
            fig_wnd = go.Figure(go.Scattermapbox(
                lat=stats_df["lat"], lon=stats_df["lon"],
                mode="markers",
                marker=dict(
                    size=20, symbol="square",
                    color=stats_df[wcf_col],
                    colorscale="Blues",
                    colorbar=dict(title="Wind CF", tickfont=dict(color="#c8d8f0"),
                                  thickness=12, bgcolor="#0d1829"),
                    opacity=0.85,
                ),
                text=[f"<b>{idx}</b><br>Wind CF: {row[wcf_col]:.3f}"
                      for idx, row in stats_df.iterrows()],
                hoverinfo="text",
            ))
            fig_wnd.update_layout(
                **PLOT_BG,
                mapbox=dict(style="carto-darkmatter", center=dict(lat=28,lon=2.5), zoom=3.8),
                height=420,
                title=dict(text="Wind Capacity Factor — Vestas V112 3MW (ERA5)", font=dict(color="#00d4b8",size=12)),
            )
            st.plotly_chart(fig_wnd, width="stretch")
    else:
        st.info("Run atlite_grid.py first to generate solar/wind resource maps.")

# ══════════════════════════════════════════════════════════════════════════════
#  TAB 3 — STATISTICS
# ══════════════════════════════════════════════════════════════════════════════
with tab3:
    st.markdown("#### LCOH Distribution Histogram")

    fig_hist = go.Figure(go.Histogram(
        x=valid["lcoh_scaled"],
        nbinsx=30,
        marker=dict(color="#f5a623", line=dict(color="#070d1a", width=0.5)),
        hovertemplate="LCOH: $%{x:.2f}/kg<br>Cells: %{y}<extra></extra>",
    ))
    fig_hist.add_vline(x=valid["lcoh_scaled"].mean(), line_dash="dot",
                       line_color="#00d4b8",
                       annotation_text=f"Mean: ${valid['lcoh_scaled'].mean():.2f}",
                       annotation_font_color="#00d4b8")
    fig_hist.update_layout(
        **PLOT_BG,
        xaxis=dict(title="LCOH (USD/kg H₂)", gridcolor="#1e3050"),
        yaxis=dict(title="Number of Grid Cells", gridcolor="#1e3050"),
        height=320,
        title=dict(text="LCOH Distribution Across Algeria", font=dict(color="#f5a623")),
    )
    st.plotly_chart(fig_hist, width="stretch")

    # LCOH vs latitude scatter
    c1, c2 = st.columns(2)
    with c1:
        st.markdown("#### LCOH vs Latitude")
        fig_lat = go.Figure(go.Scatter(
            x=valid["lat"], y=valid["lcoh_scaled"],
            mode="markers",
            marker=dict(
                color=valid["lcoh_scaled"], colorscale="RdYlGn_r",
                size=8, line=dict(color="#070d1a", width=0.5),
                showscale=False,
            ),
            hovertemplate="Lat: %{x:.1f}°N<br>LCOH: $%{y:.3f}/kg<extra></extra>",
        ))
        fig_lat.update_layout(
            **PLOT_BG, height=300,
            xaxis=dict(title="Latitude (°N)", gridcolor="#1e3050"),
            yaxis=dict(title="LCOH (USD/kg)", gridcolor="#1e3050"),
        )
        st.plotly_chart(fig_lat, width="stretch")

    with c2:
        st.markdown("#### LCOH vs Solar Full Load Hours")
        fig_flh = go.Figure(go.Scatter(
            x=valid["solar_full_load_hours"], y=valid["lcoh_scaled"],
            mode="markers",
            marker=dict(
                color=valid["lat"], colorscale="Viridis",
                size=8, line=dict(color="#070d1a", width=0.5),
                colorbar=dict(title="Lat", thickness=10,
                              tickfont=dict(color="#c8d8f0")),
            ),
            hovertemplate="FLH: %{x:.0f} h/yr<br>LCOH: $%{y:.3f}/kg<extra></extra>",
        ))
        fig_flh.update_layout(
            **PLOT_BG, height=300,
            xaxis=dict(title="Solar Full Load Hours (h/yr)", gridcolor="#1e3050"),
            yaxis=dict(title="LCOH (USD/kg)", gridcolor="#1e3050"),
        )
        st.plotly_chart(fig_flh, width="stretch")

    # ----- NEW BREAKDOWN STACKED BAR CHART -----
    st.markdown("#### LCOH Cost Breakdown Across Top 100 Regions")
    top_cells = valid.nsmallest(100, "lcoh_scaled").copy()
    top_cells["cell_label"] = top_cells["lat"].astype(str) + "N, " + top_cells["lon"].astype(str) + "E"
    
    fig_stack = go.Figure()
    components = [
        ("cost_solar_scaled", "Solar PV", "#f5a623"),
        ("cost_wind_scaled", "Wind Power", "#00d4b8"),
        ("cost_elec_scaled", "Electrolyzer", "#ff4d6d"),
        ("cost_bat_scaled", "Battery Storage", "#5a7a9a"),
        ("cost_h2t_scaled", "H2 Tank Storage", "#c8d8f0"),
        ("cost_grid_scaled", "Grid Electricity", "#ffffff"),
    ]
    for col, name, color in components:
        fig_stack.add_trace(go.Bar(
            x=top_cells["cell_label"],
            y=top_cells[col] / top_cells["h2_produced_kg"].replace(0, np.nan),
            name=name,
            marker_color=color,
        ))
    fig_stack.update_layout(
        barmode="stack",
        **PLOT_BG, height=450,
        xaxis=dict(title="Top 100 Grid Cells (Cheapest to Most Expensive)", showticklabels=False),
        yaxis=dict(title="LCOH Component (USD/kg H₂)", gridcolor="#1e3050"),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )
    st.plotly_chart(fig_stack, width="stretch")
    # -------------------------------------------

    # Full data table
    # TABLE SECTION: This renders the interactive data grid containing the full compiled dataset.
    # It is located at the bottom of Tab 3 (STATISTICS) using st.dataframe().
    st.markdown("#### Full Grid Results Table")
    display_cols = ["lat","lon","lcoh_scaled","lcoh_dzd_scaled",
                    "solar_full_load_hours","wind_cf_mean",
                    "pct_renewable","solar_capacity_kw","electrolyzer_capacity_kw"]
    display_cols = [c for c in display_cols if c in valid.columns]
    rename = {
        "lcoh_scaled":"LCOH USD/kg","lcoh_dzd_scaled":"LCOH DZD/kg",
        "solar_full_load_hours":"Solar FLH","wind_cf_mean":"Wind CF",
        "pct_renewable":"Renew. %","solar_capacity_kw":"Solar kW",
        "electrolyzer_capacity_kw":"Elec. kW",
    }
    tbl = valid[display_cols].rename(columns=rename).sort_values("LCOH USD/kg")
    st.dataframe(tbl.round(3), width="stretch", hide_index=True)
